# cities coordinates

CITIES = {
    "NYC": {
        "name": "New York City",
        "lat": 40.7826,
        "lon": -73.9656,
        "timezone": "America/New_York",
        "station": "Central Park",
    },
    "CHI": {
        "name": "Chicago",
        "lat": 41.7868,
        "lon": -87.7522,
        "timezone": "America/Chicago",
        "station": "Midway",
    },
    "LA": {
        "name": "Los Angeles",
        "lat": 33.9425,
        "lon": -118.4081,
        "timezone": "America/Los_Angeles",
        "station": "LAX",
    },
    "MIA": {
        "name": "Miami",
        "lat": 25.7959,
        "lon": -80.2870,
        "timezone": "America/New_York",
        "station": "MIA",
    },
    "AUS": {
        "name": "Austin",
        "lat": 30.1975,
        "lon": -97.6664,
        "timezone": "America/Chicago",
        "station": "Bergstrom",
    },
    "DEN": {
        "name": "Denver",
        "lat": 39.8561,
        "lon": -104.6737,
        "timezone": "America/Denver",
        "station": "DEN",
    },
    "PHL": {
        "name": "Philadelphia",
        "lat": 39.8721,
        "lon": -75.2411,
        "timezone": "America/New_York",
        "station": "PHL",
    },
    "DAL": {
        "name": "Dallas",
        "lat": 32.8998,
        "lon": -97.0403,
        "timezone": "America/Chicago",
        "station": "DFW",
    },
    "ATL": {
        "name": "Atlanta",
        "lat": 33.6407,
        "lon": -84.4277,
        "timezone": "America/New_York",
        "station": "Hartsfield",
    },
    "SF": {
        "name": "San Francisco",
        "lat": 37.6213,
        "lon": -122.3790,
        "timezone": "America/Los_Angeles",
        "station": "SFO",
    },
    "PHX": {
        "name": "Phoenix",
        "lat": 33.4373,
        "lon": -112.0078,
        "timezone": "America/Phoenix",
        "station": "Sky Harbor",
    },
    "HOU": {
        "name": "Houston",
        "lat": 29.6454,
        "lon": -95.2789,
        "timezone": "America/Chicago",
        "station": "Hobby",
    },
    "DC": {
        "name": "Washington",
        "lat": 38.8512,
        "lon": -77.0402,
        "timezone": "America/New_York",
        "station": "Reagan",
    },
    "BOS": {
        "name": "Boston",
        "lat": 42.3656,
        "lon": -71.0096,
        "timezone": "America/New_York",
        "station": "Logan",
    },
    "OKC": {
        "name": "Oklahoma City",
        "lat": 35.3931,
        "lon": -97.6008,
        "timezone": "America/Chicago",
        "station": "Will Rogers",
    },
    "LV": {
        "name": "Las Vegas",
        "lat": 36.0840,
        "lon": -115.1537,
        "timezone": "America/Los_Angeles",
        "station": "Harry Reid",
    },
    "SEA": {
        "name": "Seattle",
        "lat": 47.4502,
        "lon": -122.3088,
        "timezone": "America/Los_Angeles",
        "station": "SeaTac",
    },
    "SA": {
        "name": "San Antonio",
        "lat": 29.5337,
        "lon": -98.4698,
        "timezone": "America/Chicago",
        "station": "SAT",
    },
    "MIN": {
        "name": "Minneapolis",
        "lat": 44.8848,
        "lon": -93.2223,
        "timezone": "America/Chicago",
        "station": "MSP",
    },
    "NOLA": {
        "name": "New Orleans",
        "lat": 29.9934,
        "lon": -90.2580,
        "timezone": "America/Chicago",
        "station": "Armstrong",
    }
}